[colors.bright]
black = "#767676"
blue = "#1a8fff"
cyan = "#14ffff"
green = "#23fd00"
magenta = "#fd28ff"
red = "#f2201f"
white = "#ffffff"
yellow = "#fffd00"

[colors.normal]
black = "#000000"
blue = "#0d73cc"
cyan = "#0dcdcd"
green = "#19cb00"
magenta = "#cb1ed1"
red = "#cc0403"
white = "#dddddd"
yellow = "#cecb00"

[colors.primary]
background = "#000000"
foreground = "#ffffff"

[font]
size = 13.5

[font.normal]
family = "OperatorMono Nerd Font Mono"

[selection]
save_to_clipboard = true

[shell]
program = "fish"

[window]
opacity = 0.75

[window.dimensions]
columns = 120
lines = 40
