# theme = "solarized-dark"
[theme]
name = "modern"
[theme.overrides]
# the same as the focused window bar for i3
idle_bg = "#000000"

[icons]
name = "awesome5"

[[block]]
block = "focused_window"
max_width = 35
show_marks = "visible"
[block.theme_overrides]
idle_fg = "#2e9ef4"

[[block]]
block = "net"
format = "{speed_down;K*B}{speed_up;K*B}"
# disable built-in net icons
icons_format = " "
interval = 2
hide_missing = true
hide_inactive = true
[block.theme_overrides]
idle_fg = "#99B938"

[[block]]
block = "custom"
command = "echo "
on_click = "jumpapp -m -t Btop alacritty -t Btop -e btop"

[[block]]
block = "custom"
# need to escape ampersand
command = "echo "
on_click = "jumpapp -m -t RangerFM alacritty -t RangerFM -e ranger"

[[block]]
block = "cpu"
interval = 2
info = 30
warning = 50
critical = 90
format = "{utilization}"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used}"
format_swap = "{swap_used}"
warning_mem = 80.0
warning_swap = 50.0
critical_mem = 95.0
critical_swap = 70.0
interval = 5

[[block]]
block = "disk_space"
format = "{icon}{available}"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 10
warning = 10.0
alert = 2.0
alert_absolute = true

[[block]]
block = "music"
buttons = ["prev", "play", "next"]
dynamic_width = true
# smart_trim = true
hide_when_empty = true
interface_name_exclude = [".*chromium.*", ".*firefox.*", "vlc"]

[[block]]
block = "sound"
on_click = "pavucontrol"
max_vol = 150
show_volume_when_muted = true

[[block]]
block = "bluetooth"
mac = "60:AB:D2:0F:72:EB"
format = ""

# [[block]]
# block = "nvidia_gpu"
# label = "RTX2060"
# interval = 5
# # show_fan_speed = true
# # show_power_draw = true

[[block]]
block = "time"
interval = 5
icons_format = " "
format = "%m/%d %a %H:%M"
[block.format]
full = "%m/%d %a %H:%M"
short = "%H:%M"
