double_click_delay = 200
# fix the icon space issue: i3status-rust/issues/1669
icons_format = "<span font_family='Font Awesome 6 Pro'>{icon}</span>"
[theme]
theme = "modern"
[theme.overrides]
# use txt_ia and hdr_hi from i3/config
idle_fg = "#FFFFFF"
idle_bg = "#353535"
separator = ""

[icons]
icons = "awesome6"

[[block]]
block = "net"
# format = "$speed_down.eng(1,B,K) $speed_up.eng(1,B,K) "
format = "$speed_down.eng(prefix:K) $speed_up.eng(prefix:K,w:1) "
# disable built-in net icons
# icons_format = " "
interval = 2
# missing_format = ""
[block.theme_overrides]
# use txt_ia from i3/config
idle_fg = "#FFFFFF"
[[block.click]]
button = "double_left"
cmd = "rofi -show window -theme ~/Dotfiles.d/misc/rofi-theme-solarized_alternate.rasi -theme-str 'window {width: 33%; height: 33%;} listview {scrollbar:false;} configuration {sidebar-mode:false;}' -p 'WINDOW'"
[[block.click]]
button = "left"
cmd = "i3-msg workspace prev"
[[block.click]]
button = "right"
cmd = "i3-msg workspace back_and_forth"
[[block.click]]
button = "middle"
# monitor network speed, notify when network is less than 5MB/s
cmd = "speed_net -t"

[[block]]
block = "focused_window"
# TODO: 20 doesn't work at all
format = "$title.str(max_w:80) |"
[block.theme_overrides]
# use txt_hi from i3/confie_fg = "#2e9ef4"
idle_fg = "#2e9ef4"
[[block.click]]
# toggle layout
button = "left"
cmd = "i3-msg layout toggle tabbed split"
[[block.click]]
button = "middle"
# kill the focused window in the focused_window title
cmd = "sleep 0.1 && i3-msg [id=\"$(xdotool getactivewindow)\"] kill"
[[block.click]]
button = "double_left"
# use mouse to kill a window(not pid)
# NOTE: the sleep is a must, otherwise mouse-select won't work
# DO NOT use other method such as `xdotool selectwindow windowclose`, it will close process instead of window, such as "About Mozill Firefox" which might be the sepatated window of firefox
cmd = "sleep 0.1 && i3-msg [id=\"$(xdotool selectwindow)\"] kill"
[[block.click]]
# toggle floating the focused_window
button = "right"
cmd = "~/.config/i3/i3-scratchpad -t"

[[block]]
block = "music"
# TODO: number in str is not working
# TODO: when starting a player, "Failed to render full text" unless reload the bar, clicking show msg
# format = "$icon $prev $title.str(5)-$artist.str(5) $play $next |"
format = "{$icon $prev $combo.str(max_w:50) $play $next |}"
# `busctl --user list | grep "org.mpris.MediaPlayer2." | cut -d' ' -f1` to get current running clients
# only display
player = "audacious"
# interface_name_exclude = [".*chromium*.", ".*firefox*.", "vlc"]
[block.theme_overrides]
# using txt_hi and bgc_df from i3/config
info_fg = "#2E9EF4"
info_bg = "#353535"

[[block]]
block = "cpu"
# format = "$icon $utilization.eng(1) "
format = "$icon $utilization.eng(w:1) "
# use a long interval value since some process such as
# fd(in terminal or rofi-files) will increase CPU usage for short time
interval = 10
[block.theme_overrides]
warning_fg = "#2E9EF4"
warning_bg = "#353535"
alert_fg = "#ff0000"
alert_bg = "#353535"

[[block.click]]
button = "left"
cmd = "~/.config/i3/i3-scratchpad -d75%x75% -f kitty -T=Btop btop"

[[block]]
block = "memory"
format = "$icon $mem_used_percents.eng(w:1) "
format_alt = "$icon_swap $swap_used_percents.eng(w:1) "
warning_mem = 80.0
critical_mem = 90.0
warning_swap = 50.0
critical_swap = 80.0
interval = 10

[[block]]
block = "disk_space"
info_type = "available"
# format = "$icon $available.eng(1,auto,1i) "
format = "$icon $available.eng(w:1, prefix:1i) "
interval = 5
warning = 10.0
alert = 2.0
alert_unit = "GiB"
[[block.click]]
button = "left"
cmd = "~/.config/i3/i3-scratchpad -d75%x75% -f kitty -T=YaziFM yazi"
# [[block.click]]
# button = "right"
# TODO: not work
# cmd = "df -h | grep '/mnt/LocalDisk' | awk '{print $4}'"
# cmd = "df -h --output=avail /mnt/LocalDisk/ | grep -v Avail"
[block.theme_overrides]
warning_fg = "#2E9EF4"
warning_bg = "#353535"
alert_fg = "#ff0000"
alert_bg = "#353535"

[[block]]
block = "sound"
format = "$icon $volume "
max_vol = 150
show_volume_when_muted = true
headphones_indicator = true
[[block.click]]
# right click is to mute
button = "left"
cmd = "pavucontrol"
[[block.click]]
# middle click to mute genshinimpact/yuanshen
button = "middle"
# the grep part is "grep -Po 'pid:\s*\K\d+'" but need to add \ for cmd part
cmd = "wpctl set-mute --pid $(wpctl status | rg -i -e 'genshin|yuanshen|elden ring' | grep -Po 'pid:\\s*\\K\\d+') toggle"

[[block]]
block = "bluetooth"
format = "$icon"
disconnected_format = "$icon"
mac = "60:AB:D2:0F:72:EB"
[block.theme_overrides]
# using txt_hi and bgc_df from i3/config
good_fg = "#2E9EF4"
good_bg = "#353535"
[[block.click]]
# default is to toggle on/off
# but sometimes suddenly no sound, so use right click to connect/reconnect anyway
button = "right"
cmd = "toggle_bt_connection.sh"

# [[block]]
# block = "nvidia_gpu"
# label = "RTX2060"
# interval = 5
# # show_fan_speed = true
# # show_power_draw = true

[[block]]
block = "battery"
# battery for xbox one series game controller
# NOTE: need upower installed and service started
# device is in /sys/class/power_supply/
device = "gip*"
# device = "nintendo*"
format = "$icon $percentage"
missing_format = " "
driver = "sysfs"
critical = 10
# warning = 100
# good = 100
[block.theme_overrides]
good_fg = "#FFFFFF"
good_bg = "#353535"
# warning_fg/bg are not working
warning_fg = "#2E9EF4"
warning_bg = "#353535"
# using txt_hi and bgc_df from i3/config
critical_fg = "#ff0000"
critical_bg = "#353535"

[[block]]
block = "time"
format = "$timestamp.datetime(f:'%m/%d %a %H:%M')"
interval = 10
# [block.format]
# full = "%m/%d %a %H:%M"
# short = "%H:%M"
[[block.click]]
button = "left"
cmd = "kitty --hold sh -c 'cal -my'"
[[block.click]]
button = "right"
cmd = "kitty sh -c 'calc'"

[[block]]
block = "packages"
package_manager = ["pacman", "aur"]
# sync db everyday
interval = 86400
format = " $icon$pacman.eng(w:1)/$aur.eng(w:1)"
format_up_to_date = ""
aur_command = "yaru -Qua"
[block.theme_overrides]
# using txt_hi and bgc_df from i3/config
info_fg = "#2E9EF4"
info_bg = "#353535"
[[block.click]]
button = "left"
# Enter to update the package in ther list, Escape to quit
cmd = "rofis -u"
update = true
sync = true
[[block.click]]
button = "middle"
cmd = "kitty --hold sh -c 'paru -Syu --noconfirm'"
update = true
sync = true
[[block.click]]
button = "right"
# cmd = "kitty fakeroot -- pacman -Sy --dbpath /tmp/checkup-db-i3statusrs --logfile /dev/null"
update = true
