# theme = "solarized-dark"
[theme]
name = "modern"
[theme.overrides]
# the same as the focused window bar for i3
idle_bg = "#000000"
separator = ""

[icons]
name = "awesome5"

[[block]]
block = "focused_window"
max_width = 500
show_marks = "visible"
[block.theme_overrides]
idle_fg = "#2e9ef4"

[[block]]
block = "net"
format = "{speed_down;K*B}{speed_up;K*B}"
# disable built-in net icons
icons_format = " "
interval = 2
hide_missing = true
hide_inactive = true
[block.theme_overrides]
idle_fg = "#99B938"

[[block]]
block = "cpu"
format = "{utilization:1}"
interval = 2
info = 30
warning = 50
critical = 90
on_click = "jumpapp -m -t Btop kitty -T=Btop btop"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used:1}"
format_swap = "{swap_used:1}"
warning_mem = 90.0
warning_swap = 50.0
critical_mem = 100.0
critical_swap = 80.0
interval = 5

[[block]]
block = "disk_space"
format = "{icon:2}{available:1}"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 10
warning = 10.0
alert = 2.0
alert_absolute = true
on_click = "jumpapp -m -t RangerFM kitty -T=RangerFM ranger"

[[block]]
block = "music"
buttons = ["prev", "play", "next"]
dynamic_width = true
# smart_trim = true
marquee = false
max_width = 30
hide_when_empty = true
# `busctl --user list | grep "org.mpris.MediaPlayer2." | cut -d' ' -f1` to get current running clients
interface_name_exclude = [".*chromium*.", ".*edge*.", ".*firefox*.", "vlc"]

[[block]]
block = "sound"
format = "{volume:1}"
on_click = "pavucontrol"
max_vol = 150
show_volume_when_muted = true

[[block]]
block = "bluetooth"
format = ""
mac = "60:AB:D2:0F:72:EB"

# [[block]]
# block = "nvidia_gpu"
# label = "RTX2060"
# interval = 5
# # show_fan_speed = true
# # show_power_draw = true

[[block]]
block = "time"
format = "%m/%d %a %H:%M"
interval = 5
icons_format = " "
# [block.format]
# full = "%m/%d %a %H:%M"
# short = "%H:%M"
