# prevent Esc to quit on top level, quit with q instead
quitOnTopLevelReturn: false
gui:
  theme:
    selectedLineBgColor:
      - reverse
    selectedRangeBgColor:
      - reverse
git:
  paging:
    colorArg: never
    pager: ydiff -p cat
