# https://rust-lang.github.io/rustfmt/?version=v1.4.15
# NOTE the rustfmt version, some of variables might not work or new added
#
# And there are stable and nightly versions depending on your rustfmt version:
# current: stable channel
# required_version = "1.4.15"
#
# Stable:(commented one uses the default value)
#
edition = "2018"
# fn_args_layout = "Tall"
# force_explicit_abi = true
# hard_tabs = false
# max_width = 100
# merge_derives = true
newline_style = "Native"
# remove_nested_parens = true
# reorder_imports = true
# reorder_modules = true
# tab_spaces = 4
# use_field_init_shorthand = false
# use_small_heuristics = "Default"
# use_try_shorthand = false
#
# Unsable/Nightly:
#
# array_width = 60
# attr_fn_like_width = 70
# binop_separator = "Front"
# blank_lines_upper_bound = 2
# blank_lines_lower_bound = 1
# brace_style = "SameLineWhere"
# chain_width = 60
# color = "Auto"
# combine_control_expr = true
# comment_width = 100
# condense_wildcard_suffixes = false
# control_brace_style = "AlwaysSameLine"
# disable_all_formatting = false
# emit_mode = "Files"
# empty_item_single_line = true
# enum_discrim_align_threshold = 20
# error_on_line_overflow = false
# error_on_unformatted = false
# fn_params_layout = "Tall"
# fn_call_width = 60
# fn_single_line = false
# force_multiline_blocks = false
# format_code_in_doc_comments = false
# format_generated_files = false
# format_macro_matchers = false
# format_macro_bodies = true
# format_strings = false
# hide_parse_errors = false
# ignore = []
# imports_indent = "Block"
# imports_layout = "Mixed"
# indent_style = "Block"
# inline_attribute_width = 0
# license_template_path = ""
# make_backup = false
# match_arm_blocks = true
# match_arm_leading_pipes = "Always"
# match_block_trailing_comma = true
# merge_imports = false
# normalize_comments = true
# normalize_doc_attributes = false
# preserve_block_start_blank_lines = false
# overflow_delimited_expr = false
# reorder_impl_items = true
# report_fixme = "Never"
# report_todo = "Never"
# single_line_if_else_max_width = 50
# skip_children = false
# space_after_colon = true
# space_before_colon = false
# space_before_fn_sig_paren = false
# spaces_around_ranges = false
# spaces_around_attr_eq = true
# struct_field_align_threshold = 20
# struct_lit_single_line = true
# struct_lit_width = 18
# struct_variant_width = 35
# trailing_comma = "Vertical"
# # TODO:
# trailing_semicolon = true
# type_punctuation_density = "Wide"
# # NOTE:
# unstable_features = true
# version = "One"
# width_heuristics = "off"
# where_single_line = true
# wrap_comments = false
